language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jas' ]; then cd .. && eval "mv $currentfolder generator-jas" && cd generator-jas; fi

